name: Docker Build and Release

on:
  push:
    branches:
      - master  # or the name of your default branch

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: frenchbaker/warthog:latest  # replace with your DockerHub username and image name

    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Docker Build
      run: DOCKER_BUILDKIT=1 docker build . --output build

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ env.BRANCH_NAME }}
          release_name: Release ${{ env.BRANCH_NAME }}
          body: |
            Changes in this Release
            - Add your changes here
    - name: Upload Docker Build Output WALLET
      id: upload-docker-build-output-wallet
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./build/wart-wallet
        asset_name: wart-wallet-linux
        asset_content_type: application/octet-stream
    - name: Upload Docker Build Output NODE
      id: upload-docker-build-output-node
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./build/wart-node
        asset_name: wart-node-linux
        asset_content_type: application/octet-stream
    - name: Upload Docker Build Output MINER
      id: upload-docker-build-output-MINER
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./build/wart-miner-linux
        asset_name: wart-miner-linux
        asset_content_type: application/octet-stream
          